autohakifast = v62.Farming:AddToggle('autohakitoggle', {
    Title = 'Auto Haki',
    Default = false,
})

autohakifast:OnChanged(function(p99)
    _G.autohaki2 = p99
end)
spawn(function()
    while wait() do
        pcall(function()
            if _G.autohaki2 then
                for _ = 1, 999 do
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'On',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                    task.wait()
                    workspace:WaitForChild('UserData'):WaitForChild('User_' .. game.Players.LocalPlayer.UserId):WaitForChild('III'):FireServer(unpack({
                        'Off',
                        1,
                    }))
                end
            end
        end)
    end
end)
